package br.com.vivamulher.app;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.location.Location;
import android.location.LocationManager;
import android.media.MediaRecorder;
import android.net.Uri;
import android.os.Bundle;
import android.speech.RecognitionListener;
import android.speech.RecognizerIntent;
import android.speech.SpeechRecognizer;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    private static final int RED=Color.rgb(201,20,53), BLUE=Color.rgb(17,85,204), INK=Color.rgb(24,24,30);
    private static final int REQ_PHOTO=40, REQ_SAFETY=41, REQ_VOICE=42;
    private final ArrayList<Report> reports=new ArrayList<>();
    private SharedPreferences prefs;
    private LinearLayout root,content;
    private ScrollView scroll;
    private int themeIndex;
    private ImageView headerAvatar;
    private MediaRecorder recorder;
    private File audioFile;
    private boolean recording;
    private SpeechRecognizer speechRecognizer;
    private final Theme[] themes={
        new Theme("Branco",0xFFF7F7FB,""),new Theme("Areia",0xFFF3EBDD,""),new Theme("Cinza",0xFFE8EBF0,""),new Theme("Rosa suave",0xFFFFE9EE,""),new Theme("Azul suave",0xFFE8F1FF,""),
        new Theme("Flores",0xFFFFEEF4,"🌸  🌼  🌷"),new Theme("Folhas",0xFFEDF7ED,"🍃  🌿  🍀"),new Theme("Ursinhos",0xFFFFF0DF,"🧸  🧸  🧸"),new Theme("Borboletas",0xFFF1EDFF,"🦋  ✨  🦋"),new Theme("Corações",0xFFFFE9F0,"💗  🤍  💙")};

    @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("viva_mulher",MODE_PRIVATE);themeIndex=prefs.getInt("theme",0);load();if(prefs.getBoolean("accepted",false))build();else welcome();}
    private void welcome(){ScrollView s=new ScrollView(this);LinearLayout b=col(24);b.setGravity(Gravity.CENTER_HORIZONTAL);s.addView(b);b.addView(txt("🤝",68,RED,true));b.addView(txt("Viva Mulher",36,INK,true));b.addView(txt("Uma rede de cuidado e informação",18,BLUE,false));b.addView(gap(18));b.addView(note("Relatos são percepções pessoais e não comprovam crimes. Não publique fotos, endereço, telefone ou acusações. Em perigo imediato, ligue 190."));CheckBox ok=new CheckBox(this);ok.setText("Li e concordo com o uso responsável.");ok.setTextSize(17);b.addView(ok,wrap());Button go=btn("Começar",RED);go.setEnabled(false);ok.setOnCheckedChangeListener((x,c)->go.setEnabled(c));go.setOnClickListener(v->{prefs.edit().putBoolean("accepted",true).apply();build();});b.addView(go,full(68));setContentView(s);}
    private void build(){root=col(0);root.setBackgroundColor(themes[themeIndex].color);root.addView(header(),wrap());scroll=new ScrollView(this);content=col(16);scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));root.addView(nav(),wrap());setContentView(root);home();}
    private View header(){LinearLayout h=new LinearLayout(this);h.setPadding(dp(14),dp(10),dp(12),dp(10));h.setGravity(Gravity.CENTER_VERTICAL);h.setBackgroundColor(RED);headerAvatar=new ImageView(this);headerAvatar.setScaleType(ImageView.ScaleType.FIT_CENTER);loadPhoto(headerAvatar);h.addView(headerAvatar,new LinearLayout.LayoutParams(dp(70),dp(70)));LinearLayout title=col(0);title.setPadding(dp(10),0,dp(4),0);title.addView(txt("Viva Mulher",24,Color.WHITE,true));title.addView(txt(prefs.getString("nickname","Sua rede segura"),14,Color.WHITE,false));h.addView(title,new LinearLayout.LayoutParams(0,-2,1));Button voice=btn("🎙",BLUE);voice.setTextSize(24);GradientDrawable vg=new GradientDrawable();vg.setShape(GradientDrawable.OVAL);vg.setColor(BLUE);voice.setBackground(vg);voice.setContentDescription("Ativar comando de voz Estou em perigo");voice.setOnClickListener(v->startVoiceCommand());h.addView(voice,new LinearLayout.LayoutParams(dp(66),dp(66)));return h;}
    private View nav(){LinearLayout n=new LinearLayout(this);n.setPadding(0,dp(3),0,dp(3));n.setBackgroundColor(INK);String[] names={"⌂\nInício","＋\nAvaliar","⌕\nBuscar","♥\nAprender","☺\nPerfil"};View.OnClickListener[] ls={v->home(),v->form(),v->search(),v->learn(),v->profile()};for(int i=0;i<names.length;i++){Button b=btn(names[i],INK);b.setTextSize(11);b.setMinHeight(dp(62));b.setOnClickListener(ls[i]);n.addView(b,new LinearLayout.LayoutParams(0,dp(68),1));}return n;}

    private void home(){clear();pattern();content.addView(note("🎙 Toque no microfone azul no alto e diga “Estou em perigo”. O botão vermelho de emergência aparecerá para confirmação."));LinearLayout composer=card();composer.addView(txt("Como foi sua última corrida?",20,INK,true));composer.addView(txt("Compartilhe uma avaliação de segurança com responsabilidade.",15,Color.DKGRAY,false));Button add=btn("＋  Avaliar motorista",BLUE);add.setOnClickListener(v->form());composer.addView(add,wrap());content.addView(composer);content.addView(section("Resumo das avaliações"));content.addView(statsCard());content.addView(section("Ranking semanal de atenção"));ArrayList<Report> week=new ArrayList<>();long cutoff=System.currentTimeMillis()-7L*24*60*60*1000;for(Report r:reports)if(r.time>=cutoff)week.add(r);week.sort(Comparator.comparingInt(r->r.score));if(week.isEmpty())content.addView(note("Nenhuma avaliação registrada nos últimos sete dias neste aparelho."));for(int i=0;i<Math.min(5,week.size());i++)content.addView(post(week.get(i)));content.addView(note("🌐 A lista comunitária entre todas as usuárias aparecerá aqui quando o servidor seguro estiver ativado."));content.addView(section("No feed esta semana"));content.addView(article("Direito em destaque","A Lei Maria da Penha reconhece formas de violência física, psicológica, sexual, patrimonial e moral.","⚖️"));content.addView(article("Mulher que fez história","Bertha Lutz foi cientista e uma das principais articuladoras dos direitos políticos das mulheres no Brasil.","👩‍🔬"));}
    private void form(){clear();pattern();content.addView(section("Nova avaliação"));Spinner company=new Spinner(this);company.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Uber","99","inDrive","Maxim","Outro"}));content.addView(field("Aplicativo",company));EditText name=input("Primeiro nome do motorista",InputType.TYPE_CLASS_TEXT),plate=input("Placa — exemplo ABC1D23",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_CHARACTERS),city=input("Cidade",InputType.TYPE_CLASS_TEXT),state=input("Estado — exemplo AM",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_CHARACTERS),country=input("País",InputType.TYPE_CLASS_TEXT);country.setText("Brasil");content.addView(name,wrap());content.addView(plate,wrap());content.addView(city,wrap());content.addView(state,wrap());content.addView(country,wrap());TextView value=txt("5 — atenção",21,Color.rgb(210,110,0),true);content.addView(value);SeekBar bar=new SeekBar(this);bar.setMax(9);bar.setProgress(4);content.addView(bar,full(58));bar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean f){int s=p+1;value.setText(s+" — "+level(s));value.setTextColor(scoreColor(s));}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});CheckBox real=new CheckBox(this);real.setText("Confirmo que vivi esta experiência e não incluí acusações.");real.setTextSize(16);content.addView(real);Button save=btn("Salvar avaliação",RED);save.setOnClickListener(v->{String p=plate.getText().toString().replaceAll("[^A-Za-z0-9]","").toUpperCase(Locale.ROOT),nm=name.getText().toString().trim(),ct=city.getText().toString().trim(),st=state.getText().toString().trim().toUpperCase(Locale.ROOT),co=country.getText().toString().trim();if(p.length()!=7||nm.length()<2||ct.isEmpty()||st.isEmpty()||co.isEmpty()||!real.isChecked()){toast("Preencha motorista, placa, cidade, estado, país e confirmação.");return;}reports.add(new Report(company.getSelectedItem().toString(),nm,p,ct,st,co,bar.getProgress()+1,System.currentTimeMillis()));saveReports();toast("Avaliação salva.");home();});content.addView(save,wrap());}
    private void search(){clear();pattern();content.addView(section("Buscar motorista"));EditText plate=input("Digite a placa completa",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_CHARACTERS);content.addView(plate,full(68));Button go=btn("Pesquisar",BLUE);content.addView(go,full(68));LinearLayout result=col(8);content.addView(result);go.setOnClickListener(v->{result.removeAllViews();String q=plate.getText().toString().replaceAll("[^A-Za-z0-9]","").toUpperCase(Locale.ROOT);int n=0;for(Report r:reports)if(r.plate.equals(q)){result.addView(post(r));n++;}if(n==0)result.addView(note("Nenhum relato encontrado neste aparelho. A consulta comunitária dependerá da ativação do servidor."));});}
    private void learn(){clear();pattern();content.addView(section("Direitos e conceitos"));content.addView(article("Lei Maria da Penha","Prevê prevenção e proteção contra violência doméstica e familiar, incluindo medidas protetivas de urgência.","⚖️"));content.addView(article("Violência psicológica","Ameaçar, constranger, humilhar, manipular ou controlar de modo que prejudique a saúde psicológica e a autonomia pode configurar violência psicológica.","🧠"));content.addView(article("Importunação sexual","Praticar ato de natureza sexual sem consentimento, para satisfazer desejo próprio ou de outra pessoa, é crime.","🛑"));content.addView(article("Perseguição — stalking","Perseguir repetidamente, ameaçar integridade, restringir locomoção ou invadir liberdade e privacidade é crime.","👁"));content.addView(article("Misoginia","É aversão, desprezo ou preconceito contra mulheres. Pode aparecer em falas, instituições, controle, exclusão e violência.","📖"));content.addView(article("Patriarcado","Conceito histórico e social usado para analisar estruturas que concentraram autoridade, propriedade e poder político nos homens.","🏛"));content.addView(section("Mulher da semana"));content.addView(article("Maria da Penha Maia Fernandes","Sua luta por justiça tornou-se símbolo do enfrentamento à violência doméstica e deu nome à lei brasileira de proteção às mulheres.","🌺"));content.addView(note("Conteúdo educativo geral; não substitui orientação jurídica. Emergência: Polícia Militar 190. Central de Atendimento à Mulher: 180."));}
    private void profile(){clear();pattern();content.addView(section("Meu perfil"));ImageView photo=new ImageView(this);photo.setScaleType(ImageView.ScaleType.CENTER_CROP);loadPhoto(photo);content.addView(photo,full(180));Button choose=btn("Escolher foto do celular",BLUE);choose.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,REQ_PHOTO);});content.addView(choose,full(66));EditText nick=input("Nome ou apelido",InputType.TYPE_CLASS_TEXT);nick.setText(prefs.getString("nickname",""));content.addView(nick,full(66));EditText bio=input("Descrição opcional",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);bio.setSingleLine(false);bio.setMinLines(3);bio.setText(prefs.getString("bio",""));content.addView(bio,full(112));Button save=btn("Salvar perfil",RED);save.setOnClickListener(v->{prefs.edit().putString("nickname",nick.getText().toString().trim()).putString("bio",bio.getText().toString().trim()).apply();build();});content.addView(save,full(68));content.addView(section("Aparência — 10 opções"));for(int i=0;i<themes.length;i++){final int idx=i;Button t=btn((i==themeIndex?"✓  ":"")+themes[i].name+"  "+themes[i].pattern,Color.rgb(70,70,82));t.setOnClickListener(v->{themeIndex=idx;prefs.edit().putInt("theme",idx).apply();build();});content.addView(t,full(62));}content.addView(section("Contatos de emergência"));EditText[] phones=new EditText[3];for(int i=0;i<3;i++){phones[i]=input("Telefone de emergência "+(i+1),InputType.TYPE_CLASS_PHONE);phones[i].setText(prefs.getString("phone"+i,""));content.addView(phones[i],full(64));}Button contacts=btn("Salvar contatos",BLUE);contacts.setOnClickListener(v->{SharedPreferences.Editor e=prefs.edit();for(int i=0;i<3;i++)e.putString("phone"+i,phones[i].getText().toString().replaceAll("[^0-9+]",""));e.apply();toast("Contatos salvos.");});content.addView(contacts,full(68));}

    private void panic(){new AlertDialog.Builder(this).setTitle("ACIONAR PÂNICO?").setMessage("O app iniciará uma gravação local e preparará uma mensagem com sua localização para os contatos escolhidos. O Android pedirá confirmação para enviar. Para a polícia, será aberta uma ligação para 190.").setNegativeButton("Cancelar",null).setPositiveButton("Acionar",(d,w)->requestSafety()).show();}
    private void requestSafety(){ArrayList<String> m=new ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)m.add(Manifest.permission.RECORD_AUDIO);if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)m.add(Manifest.permission.ACCESS_FINE_LOCATION);if(!m.isEmpty()){requestPermissions(m.toArray(new String[0]),REQ_SAFETY);return;}activatePanic();}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_SAFETY)activatePanic();if(r==REQ_VOICE&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)startVoiceCommand();}
    private void startVoiceCommand(){if(!SpeechRecognizer.isRecognitionAvailable(this)){toast("Reconhecimento de voz não está disponível neste aparelho.");return;}if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_VOICE);return;}if(speechRecognizer!=null)speechRecognizer.destroy();speechRecognizer=SpeechRecognizer.createSpeechRecognizer(this);speechRecognizer.setRecognitionListener(new RecognitionListener(){public void onReadyForSpeech(Bundle b){toast("Diga: Estou em perigo");}public void onBeginningOfSpeech(){}public void onRmsChanged(float r){}public void onBufferReceived(byte[] b){}public void onEndOfSpeech(){}public void onError(int e){toast("Não consegui ouvir. Toque no microfone e tente novamente.");}public void onResults(Bundle b){ArrayList<String> xs=b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(xs!=null)for(String x:xs)if(normalize(x).contains("estou em perigo")){showVoicePanic();return;}toast("Frase não reconhecida. Diga exatamente: Estou em perigo");}public void onPartialResults(Bundle b){}public void onEvent(int e,Bundle b){}});Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"pt-BR");i.putExtra(RecognizerIntent.EXTRA_PARTIAL_RESULTS,false);i.putExtra(RecognizerIntent.EXTRA_PROMPT,"Diga: Estou em perigo");speechRecognizer.startListening(i);}
    private String normalize(String s){return java.text.Normalizer.normalize(s.toLowerCase(Locale.ROOT),java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","");}
    private void showVoicePanic(){Button big=new Button(this);big.setText("!\nPÂNICO");big.setTextColor(Color.WHITE);big.setTextSize(30);big.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable g=new GradientDrawable();g.setShape(GradientDrawable.OVAL);g.setColor(RED);g.setStroke(dp(8),Color.rgb(120,0,20));big.setBackground(g);big.setOnClickListener(v->{Dialog d=(Dialog)big.getTag();if(d!=null)d.dismiss();panic();});FrameLayout box=new FrameLayout(this);box.setPadding(dp(28),dp(20),dp(28),dp(20));box.addView(big,new FrameLayout.LayoutParams(dp(260),dp(260),Gravity.CENTER));AlertDialog d=new AlertDialog.Builder(this).setTitle("Comando de emergência reconhecido").setMessage("Toque no botão para confirmar o alerta.").setView(box).setNegativeButton("Cancelar",null).create();big.setTag(d);d.show();}
    private void activatePanic(){startRecording();String message="🚨 PÂNICO — Preciso de ajuda. Minha localização: "+locationLink()+". Ligue para mim e acione a polícia.";StringBuilder nums=new StringBuilder();for(int i=0;i<3;i++){String p=prefs.getString("phone"+i,"");if(!p.isEmpty()){if(nums.length()>0)nums.append(';');nums.append(p);}}LinearLayout status=col(12);status.addView(txt(recording?"● Gravação iniciada":"Gravação não iniciada — verifique a permissão",16,recording?RED:Color.DKGRAY,true));new AlertDialog.Builder(this).setTitle("Pânico ativado").setView(status).setNeutralButton("Parar gravação",(d,w)->stopRecording()).setNegativeButton("Ligar 190",(d,w)->startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:190")))).setPositiveButton("Enviar aos contatos",(d,w)->{if(nums.length()==0){toast("Cadastre os três contatos no perfil.");return;}Intent sms=new Intent(Intent.ACTION_SENDTO,Uri.parse("smsto:"+nums));sms.putExtra("sms_body",message);startActivity(sms);}).show();}
    private void startRecording(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)return;try{audioFile=new File(getExternalFilesDir(null),"alerta-"+System.currentTimeMillis()+".m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setOutputFile(audioFile.getAbsolutePath());recorder.prepare();recorder.start();recording=true;}catch(Exception e){recording=false;}}
    private void stopRecording(){if(!recording)return;try{recorder.stop();}catch(Exception ignored){}try{recorder.release();}catch(Exception ignored){}recording=false;toast("Áudio salvo no aplicativo.");}
    private String locationLink(){if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return "localização indisponível";try{LocationManager lm=(LocationManager)getSystemService(LOCATION_SERVICE);Location best=null;for(String p:lm.getProviders(true)){Location l=lm.getLastKnownLocation(p);if(l!=null&&(best==null||l.getAccuracy()<best.getAccuracy()))best=l;}if(best!=null)return "https://maps.google.com/?q="+best.getLatitude()+","+best.getLongitude();}catch(Exception ignored){}return "localização ainda indisponível";}
    @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==REQ_PHOTO&&c==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}prefs.edit().putString("photo",u.toString()).apply();profile();}}
    private void loadPhoto(ImageView v){String p=prefs.getString("photo","");if(!p.isEmpty()){try{v.setImageURI(Uri.parse(p));return;}catch(Exception ignored){}}v.setImageResource(R.drawable.avatar_seguranca);v.setBackgroundColor(Color.WHITE);}

    private void clear(){content.removeAllViews();content.setBackgroundColor(themes[themeIndex].color);scroll.scrollTo(0,0);}
    private void pattern(){if(!themes[themeIndex].pattern.isEmpty()){TextView p=txt(themes[themeIndex].pattern,25,INK,false);p.setGravity(Gravity.CENTER);p.setPadding(0,4,0,10);content.addView(p);}}
    private LinearLayout card(){LinearLayout c=col(16);GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(dp(18));g.setStroke(dp(1),0xFFE6E8F0);c.setBackground(g);c.setElevation(dp(2));LinearLayout.LayoutParams p=wrap();p.setMargins(0,0,0,dp(14));c.setLayoutParams(p);return c;}
    private View post(Report r){LinearLayout c=card(),row=new LinearLayout(this);TextView badge=txt(String.valueOf(r.score),24,Color.WHITE,true);badge.setGravity(Gravity.CENTER);GradientDrawable bg=new GradientDrawable();bg.setColor(scoreColor(r.score));bg.setCornerRadius(dp(16));badge.setBackground(bg);row.addView(badge,new LinearLayout.LayoutParams(dp(60),dp(60)));LinearLayout d=col(0);d.setPadding(dp(12),0,0,0);d.addView(txt(r.company+" • "+r.name,19,INK,true));d.addView(txt(mask(r.plate)+" • "+level(r.score),16,scoreColor(r.score),true));d.addView(txt(locationText(r),14,Color.DKGRAY,false));row.addView(d,new LinearLayout.LayoutParams(0,-2,1));c.addView(row);c.addView(txt("Relato de segurança • "+new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date(r.time)),13,Color.DKGRAY,false));return c;}
    private View statsCard(){LinearLayout c=card();int positive=0,negative=0;HashMap<String,int[]> states=new HashMap<>();for(Report r:reports){if(r.score>=7)positive++;if(r.score<=4)negative++;if(!r.state.isEmpty()){int[] x=states.computeIfAbsent(r.state,k->new int[2]);if(r.score>=7)x[0]++;if(r.score<=4)x[1]++;}}c.addView(txt("⭐ "+positive+" positivas     ⚠ "+negative+" negativas",18,INK,true));String pos="—",neg="—";int pv=0,nv=0;for(Map.Entry<String,int[]> e:states.entrySet()){if(e.getValue()[0]>pv){pv=e.getValue()[0];pos=e.getKey();}if(e.getValue()[1]>nv){nv=e.getValue()[1];neg=e.getKey();}}c.addView(txt("Estado com mais positivas: "+pos,15,Color.rgb(0,125,90),true));c.addView(txt("Estado com mais negativas: "+neg,15,RED,true));return c;}
    private String locationText(Report r){StringBuilder s=new StringBuilder("📍 ");if(!r.city.isEmpty())s.append(r.city);if(!r.state.isEmpty())s.append(s.length()>2?" / ":"").append(r.state);if(!r.country.isEmpty())s.append(s.length()>2?" • ":"").append(r.country);return s.length()>2?s.toString():"📍 Local não informado";}
    private View article(String title,String body,String icon){LinearLayout c=card();c.addView(txt(icon+"  "+title,20,INK,true));c.addView(txt(body,16,Color.DKGRAY,false));return c;}
    private TextView section(String s){TextView t=txt(s,23,INK,true);t.setPadding(2,16,0,12);return t;}
    private TextView note(String s){TextView t=txt(s,16,INK,false);t.setPadding(18,16,18,16);t.setBackgroundColor(Color.WHITE);LinearLayout.LayoutParams p=wrap();p.setMargins(0,0,0,12);t.setLayoutParams(p);return t;}
    private View field(String s,View v){LinearLayout l=col(0);l.addView(txt(s,14,Color.DKGRAY,true));l.addView(v,full(58));return l;}
    private EditText input(String h,int type){EditText e=new EditText(this);e.setHint(h);e.setTextSize(17);e.setTextColor(INK);e.setHintTextColor(Color.GRAY);e.setInputType(type);e.setSingleLine(true);e.setPadding(14,4,14,4);return e;}
    private Button btn(String s,int color){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(16);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setAllCaps(false);b.setMinHeight(58);b.setBackgroundTintList(ColorStateList.valueOf(color));return b;}
    private TextView txt(String s,int z,int c,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setLineSpacing(2,1.05f);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
    private LinearLayout col(int p){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(p),dp(p),dp(p),dp(p));return l;}
    private Space gap(int h){Space s=new Space(this);s.setLayoutParams(full(h));return s;}
    private LinearLayout.LayoutParams full(int h){return new LinearLayout.LayoutParams(-1,dp(h));}
    private LinearLayout.LayoutParams wrap(){return new LinearLayout.LayoutParams(-1,-2);}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
    private String mask(String p){return p.length()==7?p.substring(0,3)+"••"+p.substring(5):"•••••••";}
    private String level(int s){if(s<=2)return "perigo extremo";if(s<=4)return "alto risco percebido";if(s<=6)return "atenção";if(s<=8)return "confiável";return "muito confiável";}
    private int scoreColor(int s){if(s<=3)return RED;if(s<=6)return Color.rgb(220,120,0);if(s<=8)return BLUE;return Color.rgb(0,125,90);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private void saveReports(){JSONArray a=new JSONArray();for(Report r:reports)a.put(r.json());prefs.edit().putString("reports",a.toString()).apply();}
    private void load(){try{JSONArray a=new JSONArray(prefs.getString("reports","[]"));for(int i=0;i<a.length();i++)reports.add(new Report(a.getJSONObject(i)));}catch(Exception ignored){}}
    @Override protected void onDestroy(){stopRecording();if(speechRecognizer!=null)speechRecognizer.destroy();super.onDestroy();}
    static class Theme{String name,pattern;int color;Theme(String n,int c,String p){name=n;color=c;pattern=p;}}
    static class Report{String company,name,plate,city,state,country;int score;long time;Report(String c,String n,String p,String ct,String st,String co,int s,long t){company=c;name=n;plate=p;city=ct;state=st;country=co;score=s;time=t;}Report(JSONObject o)throws JSONException{this(o.getString("company"),o.getString("name"),o.getString("plate"),o.optString("city",""),o.optString("state",""),o.optString("country",""),o.getInt("score"),o.getLong("time"));}JSONObject json(){JSONObject o=new JSONObject();try{o.put("company",company);o.put("name",name);o.put("plate",plate);o.put("city",city);o.put("state",state);o.put("country",country);o.put("score",score);o.put("time",time);}catch(Exception ignored){}return o;}}
}
