package com.manoel.nikolaracing;

import android.content.*;
import android.graphics.*;
import android.view.*;
import java.net.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public class GameView extends View implements Runnable {
    Paint p=new Paint(3), text=new Paint(3); Random rnd=new Random(); Thread loop; volatile boolean running=true;
    float w,h,roadLeft,roadRight,playerX,playerY,speed=7,maxSpeed=18,distance=0; int lap=1,position=1,color,decal; boolean left,right,accel,brake,nitro; long jumpUntil=0,flyUntil=0,nitroUntil=0; String name;
    ArrayList<Car> bots=new ArrayList<>(); ArrayList<Obstacle> obstacles=new ArrayList<>();
    RectF bLeft=new RectF(),bRight=new RectF(),bAccel=new RectF(),bBrake=new RectF(),bNitro=new RectF(),bJump=new RectF(),bFly=new RectF();
    boolean multiplayer,host; String hostIp; volatile float remoteX=-1,remoteY=-1,remoteSpeed=0; volatile String netMsg=""; ServerSocket server; Socket sock; BufferedReader in; PrintWriter out; ExecutorService net=Executors.newCachedThreadPool();
    static class Car{float x,y,speed;int color;String n;Car(float x,float y,float s,int c,String n){this.x=x;this.y=y;speed=s;color=c;this.n=n;}}
    static class Obstacle{float x,y;int type;Obstacle(float x,float y,int t){this.x=x;this.y=y;type=t;}}
    public GameView(Context c,String n,int col,int dec,boolean mp,boolean isHost,String ip){super(c);setFocusable(true);name=n;color=col;decal=dec;multiplayer=mp;host=isHost;hostIp=ip;text.setTypeface(Typeface.DEFAULT_BOLD);if(mp)startNetwork();loop=new Thread(this);loop.start();}
    @Override protected void onSizeChanged(int W,int H,int ow,int oh){w=W;h=H;roadLeft=w*.22f;roadRight=w*.78f;playerX=w*.5f;playerY=h*.70f;bots.clear();int[] cs={0xFF00AEEF,0xFFFFD000,0xFF8E44AD,0xFF00C853,0xFFFF6D00};for(int i=0;i<5;i++)bots.add(new Car(roadLeft+60+rnd.nextFloat()*(roadRight-roadLeft-120),h*.25f+i*70,6+rnd.nextFloat()*5,cs[i],"CPU "+(i+1)));for(int i=0;i<12;i++)obstacles.add(new Obstacle(roadLeft+70+rnd.nextFloat()*(roadRight-roadLeft-140),-i*350,i%3));layoutButtons();}
    void layoutButtons(){float bh=95;bLeft.set(15,h-bh-15,120,h-15);bRight.set(130,h-bh-15,235,h-15);bBrake.set(w-720,h-bh-15,w-590,h-15);bAccel.set(w-580,h-bh-15,w-430,h-15);bNitro.set(w-420,h-bh-15,w-300,h-15);bJump.set(w-290,h-bh-15,w-155,h-15);bFly.set(w-145,h-bh-15,w-15,h-15);}
    @Override public void run(){long prev=System.nanoTime();while(running){long now=System.nanoTime();float dt=Math.min(.033f,(now-prev)/1e9f);prev=now;update(dt);postInvalidate();try{Thread.sleep(16);}catch(Exception ignored){}}}
    void update(float dt){if(w==0)return;long now=System.currentTimeMillis();if(accel)speed+=16*dt;if(brake)speed-=22*dt;speed-=2.5f*dt;if(now<nitroUntil)speed+=25*dt;speed=Math.max(2,Math.min(maxSpeed+(now<nitroUntil?7:0),speed));if(left)playerX-=320*dt*(.4f+speed/maxSpeed);if(right)playerX+=320*dt*(.4f+speed/maxSpeed);playerX=Math.max(roadLeft+35,Math.min(roadRight-35,playerX));distance+=speed*dt*14;if(distance>2500){distance-=2500;lap++;if(lap>3)lap=3;}for(Car c:bots){c.y+=(speed-c.speed)*dt*30;if(c.y>h+80)c.y=-80;if(c.y<-100)c.y=h+80;c.x+=Math.sin((System.currentTimeMillis()+c.n.hashCode())*.001)*18*dt;}for(Obstacle o:obstacles){o.y+=speed*dt*30;if(o.y>h+100){o.y-=4200;o.x=roadLeft+70+rnd.nextFloat()*(roadRight-roadLeft-140);}if(now>jumpUntil&&now>flyUntil&&Math.abs(o.y-playerY)<38&&Math.abs(o.x-playerX)<42){speed*=.62f;o.y+=120;}}int ahead=0;for(Car c:bots)if(c.y<playerY)ahead++;position=1+ahead;if(multiplayer&&remoteY>=0&&remoteY<playerY)position++;if(multiplayer&&out!=null){try{out.println(playerX+","+playerY+","+speed+","+name);if(out.checkError())out=null;}catch(Exception ignored){}}}
    @Override protected void onDraw(Canvas c){super.onDraw(c);p.setColor(0xFF264D25);c.drawRect(0,0,w,h,p);p.setColor(0xFF3D3D43);c.drawRect(roadLeft,0,roadRight,h,p);p.setColor(Color.WHITE);c.drawRect(roadLeft,0,roadLeft+8,h,p);c.drawRect(roadRight-8,0,roadRight,h,p);p.setColor(0x77FFFFFF);for(int i=0;i<9;i++){float y=i*140+(distance*4)%140;c.drawRect(w/2-5,y-60,w/2+5,y,p);}drawHUD(c);for(Obstacle o:obstacles)drawObstacle(c,o);for(Car b:bots)drawCar(c,b.x,b.y,b.color,0,b.n,false);if(multiplayer&&remoteX>=0)drawCar(c,remoteX,remoteY,0xFF00FFFF,2,"RIVAL",false);drawCar(c,playerX,playerY,color,decal,name,System.currentTimeMillis()<flyUntil);drawControls(c);}
    void drawHUD(Canvas c){text.setColor(Color.WHITE);text.setTextSize(28);c.drawText(name,20,36,text);c.drawText("Vel: "+(int)(speed*13)+" km/h",20,72,text);c.drawText("Volta: "+lap+"/3",20,108,text);c.drawText("Posição: "+position+"º",20,144,text);if(multiplayer){text.setTextSize(20);c.drawText(netMsg,20,176,text);}}
    void drawObstacle(Canvas c,Obstacle o){if(o.type==0){p.setColor(0xFFFF8C00);Path path=new Path();path.moveTo(o.x,o.y-24);path.lineTo(o.x-20,o.y+24);path.lineTo(o.x+20,o.y+24);path.close();c.drawPath(path,p);}else if(o.type==1){p.setColor(0xFFE53935);c.drawRect(o.x-35,o.y-15,o.x+35,o.y+15,p);}else{p.setColor(0xFF8D6E63);c.drawOval(new RectF(o.x-28,o.y-18,o.x+28,o.y+18),p);}}
    void drawCar(Canvas c,float x,float y,int col,int dec,String n,boolean flying){float lift=flying?18:0;if(flying){p.setColor(0x4433AAFF);c.drawOval(new RectF(x-45,y+30,x+45,y+55),p);}p.setColor(col);c.drawRoundRect(new RectF(x-34,y-55-lift,x+34,y+55-lift),16,16,p);p.setColor(0xFFBDE8FF);c.drawRoundRect(new RectF(x-24,y-25-lift,x+24,y+8-lift),8,8,p);p.setColor(Color.DKGRAY);c.drawRect(x-40,y-34-lift,x-32,y-4-lift,p);c.drawRect(x+32,y-34-lift,x+40,y-4-lift,p);c.drawRect(x-40,y+18-lift,x-32,y+48-lift,p);c.drawRect(x+32,y+18-lift,x+40,y+48-lift,p);p.setColor(Color.WHITE);p.setStrokeWidth(5);if(dec==1)c.drawLine(x,y-50-lift,x,y+48-lift,p);else if(dec==2){c.drawLine(x-20,y+30-lift,x+12,y-20-lift,p);c.drawLine(x+12,y-20-lift,x-4,y-12-lift,p);c.drawLine(x-4,y-12-lift,x+20,y-40-lift,p);}else if(dec==3){text.setColor(Color.WHITE);text.setTextSize(28);c.drawText("7",x-8,y+15-lift,text);}else if(dec==4){c.drawLine(x-22,y-22-lift,x+22,y+22-lift,p);c.drawLine(x+22,y-22-lift,x-22,y+22-lift,p);}text.setColor(Color.WHITE);text.setTextSize(16);c.drawText(n,x-30,y-63-lift,text);}
    void drawControls(Canvas c){drawBtn(c,bLeft,"◀");drawBtn(c,bRight,"▶");drawBtn(c,bBrake,"FREAR");drawBtn(c,bAccel,"ACELERAR");drawBtn(c,bNitro,"NITRO");drawBtn(c,bJump,"SALTO");drawBtn(c,bFly,"VOAR");}
    void drawBtn(Canvas c,RectF r,String s){p.setColor(0xCC151A22);c.drawRoundRect(r,18,18,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(0xFFE0E0E0);c.drawRoundRect(r,18,18,p);p.setStyle(Paint.Style.FILL);text.setColor(Color.WHITE);text.setTextSize(s.length()>5?18:27);text.setTextAlign(Paint.Align.CENTER);c.drawText(s,r.centerX(),r.centerY()+8,text);text.setTextAlign(Paint.Align.LEFT);}
    @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();int a=e.getActionMasked();boolean down=a!=MotionEvent.ACTION_UP&&a!=MotionEvent.ACTION_CANCEL;if(a==MotionEvent.ACTION_DOWN||a==MotionEvent.ACTION_POINTER_DOWN){if(bJump.contains(x,y)){jumpUntil=System.currentTimeMillis()+900;return true;}if(bFly.contains(x,y)){flyUntil=System.currentTimeMillis()+3500;return true;}if(bNitro.contains(x,y)){nitroUntil=System.currentTimeMillis()+2200;return true;}}left=down&&bLeft.contains(x,y);right=down&&bRight.contains(x,y);accel=down&&bAccel.contains(x,y);brake=down&&bBrake.contains(x,y);nitro=down&&bNitro.contains(x,y);if(!down){left=right=accel=brake=nitro=false;}return true;}
    void startNetwork(){netMsg=host?"Criando sala...":"Conectando...";net.execute(()->{try{if(host){server=new ServerSocket(44555);netMsg="Host pronto. IP: "+localIp();sock=server.accept();}else{sock=new Socket();sock.connect(new InetSocketAddress(hostIp,44555),6000);}in=new BufferedReader(new InputStreamReader(sock.getInputStream()));out=new PrintWriter(new BufferedWriter(new OutputStreamWriter(sock.getOutputStream())),true);netMsg="Multiplayer conectado";String line;while(running&&(line=in.readLine())!=null){String[] s=line.split(",",4);if(s.length>=3){remoteX=Float.parseFloat(s[0]);remoteY=Float.parseFloat(s[1]);remoteSpeed=Float.parseFloat(s[2]);}}}catch(Exception e){netMsg="Rede: "+e.getClass().getSimpleName();}});}
    String localIp(){try{Enumeration<NetworkInterface> en=NetworkInterface.getNetworkInterfaces();while(en.hasMoreElements()){NetworkInterface ni=en.nextElement();Enumeration<InetAddress> as=ni.getInetAddresses();while(as.hasMoreElements()){InetAddress a=as.nextElement();if(!a.isLoopbackAddress()&&a instanceof Inet4Address)return a.getHostAddress();}}}catch(Exception ignored){}return "indisponível";}
    public void shutdown(){running=false;try{if(sock!=null)sock.close();if(server!=null)server.close();}catch(Exception ignored){}net.shutdownNow();}
}
